-- Rename CheckInStatus enum values: SUBMITTED→PENDING, APPROVED→COMPLETED
ALTER TYPE "CheckInStatus" RENAME VALUE 'SUBMITTED' TO 'PENDING';
ALTER TYPE "CheckInStatus" RENAME VALUE 'APPROVED' TO 'COMPLETED';
